# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
stages:
  - stage: Build_Publish
    jobs:
      - job: 
        pool:
          vmImage: 'windows-latest'

        variables:
          solution: '**/*.csproj'
          buildPlatform: 'Any CPU'
          buildConfiguration: 'Release'

        steps:
        - task: NuGetToolInstaller@1

        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(solution)'

        - task: VSBuild@1
          inputs:
            solution: '$(solution)'
            msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        - task: CopyFiles@1
          inputs:
            SourceFolder: 'ARMTemplates'
            Contents: 'azuredeploy*.json'
            TargetFolder: ' $(build.artifactstagingdirectory)'
        - task: CopyFiles@2
          inputs:
              SourceFolder: 'EmployeeDB'
              Contents: 'EmployeeDB.*'
              TargetFolder: ' $(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
  
  - stage: Dev_Deployment
    dependsOn: Build_Publish
    jobs:
      - job: Dev_Deployment
        pool:
          vmImage: 'windows-latest'

        variables: 
        - group: devemp
        
        steps: 
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)'
          - task: replacetokens@3
            displayName: 'Replace tokens in azuredeploy.parameters.json'
            inputs:
              rootDirectory: '$(Pipeline.Workspace)/drop'
              targetFiles: 'azuredeploy.parameters.json'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#'
              tokenSuffix: '#'
              useLegacyPattern: false
              enableTransforms: false
              enableTelemetry: false
          
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Free Trial(8a637732-23bb-4eac-8053-74de19434aab)'
              subscriptionId: '8a637732-23bb-4eac-8053-74de19434aab'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(arm_employeewebappname)'
              location: 'Canada Central'
              templateLocation: 'Linked artifact'
              csmFile: '$(System.ArtifactsDirectory)/*/azuredeploy.json'
              csmParametersFile: '$(System.ArtifactsDirectory)/*/azuredeploy.parameters.json'
              deploymentMode: 'Incremental'
          

