# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.csproj'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'ARMTemplates'
        Contents: 'azuredeploy*.json'
        TargetFolder: '$(build.artifactStagingDirectory)'
    
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'employeeartifact'
        publishLocation: 'Container'

- stage: Deploy
  dependsOn: [Build]
  jobs: 
  - job: Deploy
    pool:
      vmImage: 'windows-latest'
    variables:
      arm_employeewebappname : 'EmpWebApp-Dev'
      arm_employeewebappskuname : 'EmpWebAppsku-Dev'
      arm_employeesqlservername : 'EmpWebSql-Dev'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'EmployeeArtifact'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: replacetokens@3
      inputs:
        rootDirectory: '$(System.ArtifactsDirectory)'
        targetFiles: 'azuredeploy.parameters.json'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#['
        tokenSuffix: ']#'
        useLegacyPattern: false
        enableTelemetry: true
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Free Trial(8a637732-23bb-4eac-8053-74de19434aab)'
        subscriptionId: '8a637732-23bb-4eac-8053-74de19434aab'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(arm_employeewebappname)'
        location: 'South Central US'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.ArtifactsDirectory)/**/azuredeploy.json'
        csmParametersFile: '$(System.ArtifactsDirectory)/**/azuredeploy.parameters.json'
        deploymentMode: 'Incremental'
    
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Free Trial(8a637732-23bb-4eac-8053-74de19434aab)'
        appType: 'webApp'
        WebAppName: '$(arm_employeewebappname)'
        deployToSlotOrASE: true
        ResourceGroupName: '$(arm_employeewebappname)'
        SlotName: 'production'
        packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
    
    