trigger:
- NONE

stages:
- stage: Build_Publish
  jobs:
    - job: 
      pool:
        vmImage: windows-latest
      variables: 
      - group: devemp
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'specific'
          project: '9df47b7d-9963-412b-ac0a-382f4553d4a4'
          definition: '6'
          buildVersionToDownload: 'latest'
          targetPath: '$(Pipeline.Workspace)'

      - task: replacetokens@3
        displayName: 'Replace tokens in azuredeploy.parameters.json'
        inputs:
          rootDirectory: '$(Pipeline.Workspace)/drop'
          targetFiles: 'azuredeploy.parameters.json'
          encoding: 'auto'
          writeBOM: true
          actionOnMissing: 'warn'
          keepToken: false
          tokenPrefix: '#'
          tokenSuffix: '#'
          useLegacyPattern: false
          enableTransforms: false
          enableTelemetry: false

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Pipeline.Workspace)/drop'
          Contents: 'azuredeploy.parameters.json'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'