# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
stages:
  
  - stage: Dev_Deployment
    dependsOn: Build_Publish
    jobs:
      - job: Dev_Deployment
        pool:
          vmImage: 'windows-latest'

        variables: 
        - group: devemp
        
        steps: 
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: replacetokens@3
            displayName: 'Replace tokens in azuredeploy.parameters.json'
            inputs:
              rootDirectory: '$(System.ArtifactsDirectory)/*/drop'
              targetFiles: azuredeploy.parameters.json
              tokenPrefix: '#'
              tokenSuffix: '#'
          
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Free Trial(8a637732-23bb-4eac-8053-74de19434aab)'
              subscriptionId: '8a637732-23bb-4eac-8053-74de19434aab'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(arm_employeewebappname)'
              location: 'Canada Central'
              templateLocation: 'Linked artifact'
              csmFile: '$(System.ArtifactsDirectory)/*/azuredeploy.json'
              csmParametersFile: '$(System.ArtifactsDirectory)/*/azuredeploy.parameters.json'
              deploymentMode: 'Incremental'
          

